#!/bin/bash

input=$(cat)

if [ -x $(command -v bat) ]; then
    if [ -n "$1" ]; then
        echo "$input" | bat -pp --color=always --style=numbers "$1"
    else
        echo "$input" | bat -pp --color=always --style=numbers
    fi
else
    echo "$input"
fi
