#!/bin/bash

format-columns () {
    input=$(cat)

    # get the longest string in each column
    # e.g. 23|42|11
    lengths=$(echo "$input" | awk -F'|' 'NR>1{for (i=1; i<=NF; i++) max[i]=(length($i)>max[i]?length($i):max[i])} END {for (i=1; i<=NF; i++) printf "%d%s", max[i], (i==NF?RS:FS)}')
    column_count=$(($(echo "$lengths" | awk -F'|' '{print NF-1}')+1))

    column_size1=$(echo "$lengths" | awk -F'|' '{print $1}')
    column_size2=$(echo "$lengths" | awk -F'|' '{print $2}')

    # manual check for how many columns because the number is going to be limited
    # and will also be known in the source
    if [[ $column_count -eq 2 ]]; then
        echo "$input" | awk -F'|' "{printf(\"%-${column_size1}s\t%s\n\", \$1, \$2)}"
    elif [[ $column_count -eq 3 ]]; then
        column_size3=$(echo "$lengths" | awk -F'|' '{print $3}')
        echo "$input" | awk -F'|' "{printf(\"%-${column_size1}s\t%-${column_size2}s\t%s\n\", \$1, \$2, \$3)}"
    elif [[ $column_count -eq 4 ]]; then
        column_size3=$(echo "$lengths" | awk -F'|' '{print $3}')
        column_size4=$(echo "$lengths" | awk -F'|' '{print $4}')
        echo "$input" | awk -F'|' "{printf(\"%-${column_size1}s\t%-${column_size2}s%s\t%-${column_size3}\t%s\n\", \$1, \$2, \$3, \$4)}"
    else
        echo "$input"
    fi
}
