#!/bin/bash

get-remote-name () {
    remotes=$(git remote -v | uniq)
    remote=$(echo "$remotes" | grep push | fzf --preview="eval $1" --preview-window down:5)
    echo $remote | awk '{print $1}'
}
