#!/bin/bash

get-stash-ref () {
    preview="echo {1} | awk -F':' '{print \$1}' | git stash show -p"
    stashes=$(git stash list)

    if [ -x $(command -v bat) ]; then
        preview="$preview | bat -pp --color=always --style=numbers"
    fi
    stash=$(echo "$stashes" | fzf --no-hscroll --no-multi --ansi --preview "eval $preview" | awk -F':' '{print $1}') || exit
    echo "$stash"
}
