#!/bin/bash

get-tag-name () {
    tags=$(git --no-pager tag | awk '{print "\x1b[35;1mtag\x1b[m\t" $1}' | tac) || exit

    if [ -n "$2" ]; then
        preview=$2
    else
        preview=""
    fi

    target=$(
      (echo "$tags") |
      fzf --no-hscroll --no-multi -n 2 \
          --ansi --preview="eval $preview" --preview-window down:5 | awk '{print $2}') || exit

    if [ -n "$target" ]; then
        echo "$target"
    fi
}
