#!/bin/bash

get-commit-hash () {
    preview=$1
    log_entries=$(git log --pretty=format:'%h|%ad|%an|%d %Creset%s' --date=relative | column -ts '|')
    log_entry=$(echo "$log_entries" | fzf --preview="eval $preview" --preview-window down:5)
    hash=$(echo "$log_entry" | awk '{print $1}')
    echo "$hash"
}
