#!/bin/bash

SCRIPT=`realpath $0`
DIR=`dirname $SCRIPT`
source "$DIR/_tag-increment-patch"
source "$DIR/_tag-increment-minor"
source "$DIR/_tag-increment-major"

option=$(cat)

if [ "$option" == "Patch" ]; then
    new_tag=$(tag-increment-patch)
elif [ "$option" == "Minor" ]; then
    new_tag=$(tag-increment-minor)
else
    new_tag=$(tag-increment-major)
fi

echo "$new_tag"
