#!/bin/bash

get-remote-name () {
    remotes=$(git remote -v | uniq)
    remote=$(echo "$remotes" | grep push | awk -F' ' '{printf("\x1b[34;1m%s|\x1b[33;1m%-15s\x1b[m|%s\n", "remote", $1, $2)}' | format-columns | fzf --no-hscroll --no-multi --ansi --preview="eval $1" --preview-window down:5)
    echo $remote | awk '{print $2}'
}
