#!/bin/bash

run-command () {
    config_dir=~/.config/git-gud
    if [ ! -d "$config_dir" ]; then
        mkdir "$config_dir"
    fi

    branch=$(git rev-parse --abbrev-ref HEAD)
    working_dir=$(pwd)
    now=$(date '+%Y-%m-%d %H:%M:%S')
    echo "$now|$1|$branch|$working_dir" >> "$config_dir/history"
    bash -c "$1"
}
