#!/bin/bash

tag-increment-major () {
    most_recent_tag=$(git describe --tags --abbrev=0)

    # if a tag uses layout like v1.0.0, we want to keep the v but increment the 1
    # so we need to grab the v and save it for later and get the number separately
    major=$(echo "$most_recent_tag" | awk -F'.' '{print $1}' | sed "s/[^0-9]//g")
    major_prefix=$(echo "$most_recent_tag" | awk -F'.' '{print $1}' | sed "s/^\([^0-9]*\)[0-9]*/\1/g")

    new_major=$(($major+1))
    echo "${major_prefix}${new_major}.0.0"
}
