#!/bin/bash

tag-increment-patch () {
    most_recent_tag=$(git describe --tags --abbrev=0)
    major=$(echo "$most_recent_tag" | awk -F'.' '{print $1}')
    minor=$(echo "$most_recent_tag" | awk -F'.' '{print $2}')
    patch=$(echo "$most_recent_tag" | awk -F'.' '{print $3}')
    new_patch=$(($patch+1))
    echo "$major.$minor.$new_patch"
}
