#!/bin/bash

add () {
    GITDIR=$(git rev-parse --show-toplevel)
    files=$(git ls-files "$GITDIR" --exclude-standard --others -m)
    while read -r file; do
        # break up path into subdirectories
        # e.g. path/to/file becomes path\nto
        # so we can include directories in the list to add
        splits=$(echo "$file" | sed -e "s/\//\n/g" | sed '$d')
        path=""

        while read -r split; do
            # remove leading slash so path is relative
            path=$(echo "$path/$split" | sed "s#^/##g")
            if [ -n "$split" ]; then
                files=$(printf "$files\n$path")
            fi
        done <<< "$splits"
    done <<< "$files"

    # put . and .. first
    files=$(printf "$files\n." | sort -r | uniq)

    # Colorize the options, prefixing either "dir" or "file"
    list=""
    while read -r file; do
        is_tracked=$(git ls-files "$file")
        if [ -z "$is_tracked" ]; then
            file="\x1b[31;1m$file\x1b[m"
        fi

        if [ -d "$file" ]; then
            list=$(printf "\x1b[36;1mdir\x1b[m|$file\n$list")
        else
            list=$(printf "\x1b[34;1mfile\x1b[m|$file\n$list")
        fi
    done <<< "$files"

    path=$(echo "$list" | format-columns | fzf --no-hscroll --ansi --preview "$DIR/_add-preview {2}" | awk '{print $2}')

    if [ -n "$path" ]; then
        git add "$path"
    fi
}
