#!/bin/bash

add () {
    files=$(git ls-files "$DIR/../" --exclude-standard --others -m)
    while read -r file; do
        # break up path into subdirectories
        # e.g. path/to/file becomes path\nto
        # so we can include directories in the list to add
        splits=$(echo "$file" | sed -e "s/\//\n/g" | sed '$d')
        while read -r split; do
            if [ -n "$split" ]; then
                files=$(printf "$files\n$split")
            fi
        done <<< "$splits"
    done <<< "$files"

    # put . and .. first
    files=$(printf "$files\n." | uniq | sort -r)
    list=""
    while read -r file; do
        if [ -d "$file" ]; then
            list=$(printf "\x1b[36;1mdir\x1b[m\t$file\n$list")
        else
            list=$(printf "\x1b[34;1mfile\x1b[m\t$file\n$list")
        fi
    done <<< "$files"

    # list the number of files in the preview window

    path=$(echo "$list" | fzf --no-hscroll --ansi --preview "git ls-files {2} --exclude-standard --others -m | cat <(echo -n \"$1\n\ngit add {2}\n\n\") -")

    if [ -n "$path" ]; then
        git add "$path"
    fi
}
