#!/bin/bash

## git checkout tag

branch-tag () {
    target=$(get-tag-name "" 'echo "git checkout -b {2} \[branch_name\]"')
    if [ -n "$target" ]; then
        read -p "New branch name: " branch_name
        run-command "git checkout -b \"$branch_name\" $(awk '{print $2}' <<<$target )"
    fi
}
