#!/bin/bash

## git checkout tag

branch-branch () {
    target=$(get-branch-name "" 'echo "git checkout -b \[branch_name\] {2}"')
    if [ -n "$target" ]; then
        read -ep "New branch name: " branch_name
        run-command "git checkout -b \"$branch_name\" $target"
    fi
}
