#!/bin/bash

## git checkout tag

branch-tag () {
    target=$(get-tag-name "" 'echo "git checkout -b \[branch_name\] {2}"')
    if [ -n "$target" ]; then
        read -p "New branch name: " branch_name
        run-command "git checkout -b \"$branch_name\" $target"
    fi
}
