#!/bin/bash

## git checkout tag

checkout-tag () {
    target=$(get-tag-name "" 'echo "git checkout {2}"')
    if [ -n "$target" ]; then
        run-command "git checkout $(awk '{print $1}' <<<$target )"
    fi
}
