#!/bin/bash

## git checkout all branch

SCRIPT=`realpath $0`
DIR=`dirname $SCRIPT`
source "$DIR/.run-command"

target=$(get-branch-name "--all" 'echo "git checkout {2}"')
if [ -n "$target" ]; then
    run_command "git checkout $(awk '{print $2}' <<<$target )"
fi
