#!/bin/bash

## git checkout all branch

checkout-branch-remote () {
    target=$(get-branch-name "--all" "source $DIR/_checkout-branch-remote-command {2}")

    cmd=$("$DIR/_checkout-branch-remote-command" "$target")

    if [ -n "$target" ]; then
        run-command "$cmd"
    fi
}
