#!/bin/bash

cherry-pick () {
    branch=$(get-branch-name "" 'echo "Select a branch. No action is taken until selecting a commit."')

    if [ -z "$branch" ]; then
        exit
    fi

    hash=$(get-commit-hash "echo \"git cherry-pick -e {1} \"")

    if [ -n "$hash" ]; then
        run-command "git cherry-pick -e $hash"
    fi
}
