#!/bin/bash


SCRIPT=`realpath $0`
DIR=`dirname $SCRIPT`
source "$DIR/.run-command"

tags=$(git tag)
tag=$(echo "$tags" | fzf --preview='echo "Select a tag. No action is taken until selecting a remote."' --preview-window down:5)

if [ -z "$tag" ]; then
    exit
fi

remotes=$(git remote -v | uniq)
target=$(echo "$remotes" | grep push | fzf --preview="echo \"git tag -d $tag && git push {1} \":refs/tags/$tag\"\"" --preview-window down:5)

if [ -z "$target" ]; then
    exit
fi

remote=$(echo "$target" | awk '{print $1}')
run_command "git tag -d $tag"
run_command "git push $remote :refs/tags/$tag"
