#!/bin/bash

delete-tag-remote () {
    tag=$(get-tag-name "" "echo 'No action is taken until selecting a remote.'")

    if [ -z "$tag" ]; then
        exit
    fi

    remotes=$(git remote -v | uniq)
    target=$(echo "$remotes" | grep push | fzf --preview="echo \"git tag -d $tag && git push {1} \":refs/tags/$tag\"\"" --preview-window down:5)

    if [ -z "$target" ]; then
        exit
    fi

    remote=$(echo "$target" | awk '{print $1}')
    run-command "git tag -d $tag"
    run-command "git push $remote :refs/tags/$tag"
}
