#!/bin/bash

delete-tag () {
    local_tags=$(bash -c "comm -23 <(git show-ref --tags | cut -d ' ' -f 2) <(git ls-remote --tags | cut -f 2)" | awk -F"/" '{print "\x1b[35;1mtag\x1b[m\t" $3}')
    tag=$(echo "$local_tags" | fzf --ansi --preview='echo "git tag -d {1}"' --preview-window down:5)

    if [ -z "$tag" ]; then
        exit
    fi

    run-command "git tag -d $tag"
}
