#!/bin/bash

delete-tag-remote () {
    tag=$(get-tag-name "" "echo 'No action is taken until selecting a remote.'")

    if [ -z "$tag" ]; then
        exit
    fi

    remote=$(get-remote-name "echo \"git push {1} :refs/tags/$tag\"")

    if [ -z "$remote" ]; then
        exit
    fi

    run-command "git tag -d $tag"
    run-command "git push $remote :refs/tags/$tag"
}
