#!/bin/bash

## git delete local branch with -D

SCRIPT=`realpath $0`
DIR=`dirname $SCRIPT`
source "$DIR/.run-command"

target=$(get-branch-name "" 'echo "git branch -d {2}"')
if [ -n "$target" ]; then
    run_command "git branch -d $(awk '{print $2}' <<<$target )"
fi
