#!/bin/bash

SCRIPT=`realpath $0`
DIR=`dirname $SCRIPT`
source "$DIR/.run-command"

commit1=$(get-commit-hash 'echo "First of two commits to compare"')

if [ -z "$commit1" ]; then
    exit
fi

commit2=$(get-commit-hash "echo \"git difftool $commit1 {1} --dir-diff\"")

if [ -z "$commit2" ]; then
    exit
fi

run_command "git difftool $commit1 $commit2 --dir-diff"
