#!/bin/bash

difftool-commits () {
    commit1=$(get-commit-hash 'echo "First of two commits to compare"')

    if [ -z "$commit1" ]; then
        exit
    fi

    commit2=$(get-commit-hash "echo \"git difftool $commit1 {1}\"")

    if [ -z "$commit2" ]; then
        exit
    fi

    run-command "git difftool $commit1 $commit2"
}
