#!/bin/bash

diff-commits () {
    commit1=$(get-commit-hash 'echo "First of two commits to compare"')

    if [ -z "$commit1" ]; then
        exit
    fi

    commit2=$(get-commit-hash "echo \"git diff $commit1 {1}\"")

    if [ -z "$commit2" ]; then
        exit
    fi

    run-command "git diff $commit1 $commit2"
}
