#!/bin/bash

## git checkout local branch

SCRIPT=`realpath $0`
DIR=`dirname $SCRIPT`
source "$DIR/.run-command"

target=$(gg-get-branch-name "" 'echo "git checkout {2}"')
if [ -n "$target" ]; then
    run_command "git checkout $(awk '{print $2}' <<<$target )"
fi
