#!/bin/bash

local_tags=$(bash -c "comm -23 <(git show-ref --tags | cut -d ' ' -f 2) <(git ls-remote --tags origin | cut -f 2)" | awk -F"/" '{print $3}')
tag=$(echo "$local_tags" | fzf --preview="")

if [ -z "$tag" ]; then
    exit
fi

git tag -d "$tag"
