#!/bin/bash

SCRIPT=`realpath $0`
DIR=`dirname $SCRIPT`
source "$DIR/.run-command"

local_tags=$(bash -c "comm -23 <(git show-ref --tags | cut -d ' ' -f 2) <(git ls-remote --tags | cut -f 2)" | awk -F"/" '{print $3}')
tag=$(echo "$local_tags" | fzf --preview='echo "git tag -d {1}"' --preview-window down:5)

if [ -z "$tag" ]; then
    exit
fi

run_command "git tag -d $tag"
