#!/bin/bash

tags=$(
  git --no-pager tag | awk '{print "\x1b[35;1mtag\x1b[m\t" $1}' | tac) || exit
target=$(
  (echo "$tags") |
  fzf --no-hscroll --no-multi -n 2 \
      --ansi --preview="git --no-pager log -150 --pretty=format:%s '..{2}'") || exit

if [ -n "$target" ]; then
    echo "$target"
fi
