#!/bin/bash

SCRIPT=`realpath $0`
DIR=`dirname $SCRIPT`
source "$DIR/.run-command"

preview=$1
log_entries=$(git log --pretty=format:'%h|%ad|%an|%d %Creset%s' --date=relative | column -ts '|')
log_entry=$(echo "$log_entries" | fzf --preview="eval $preview" --preview-window down:5)
hash=$(echo "$log_entry" | awk '{print $1}')
echo "$hash"
