#!/bin/bash

SCRIPT=`realpath $0`
DIR=`dirname $SCRIPT`
options=$(cat "$DIR/.gg-options")
target=$(echo "$options" | fzf --preview="")

if [ -n "$target" ]; then
    bash -c $(echo "$target" | awk '{print $1}')
fi
