#!/bin/bash

SCRIPT=`realpath $0`
DIR=`dirname $SCRIPT`
options=$(cat "$DIR/.gg-options")

if [ -f ~/.gg-options ]; then
    custom_options=$(cat ~/.gg-options)
else
    custom_options=""
fi

all_options=$(printf "$options\n$custom_options")
target=$(echo "$all_options" | column -ts '|' | fzf --preview="")

if [ -n "$target" ]; then
    cmd=$(echo "$target" | awk -F"  " '{print $1}')
    bash -c "$cmd"
fi
