#!/bin/bash

SCRIPT=`realpath $0`
DIR=`dirname $SCRIPT`
source "$DIR/.run-command"

log_entries=$(git log --pretty=oneline)
log_entry=$(echo "$log_entries" | fzf --preview='echo "git reset {1}"' --preview-window down:5)
hash=$(echo "$log_entry" | awk '{print $1}')
run_command "git reset $hash"
