#!/bin/bash

remotes=$(git remote -v | uniq)
target=$(echo "$remotes" | grep push | fzf --preview="")

if [ -n "$target" ]; then
    remote=$(echo "$target" | awk '{print $1}')
    branch=$(git rev-parse --abbrev-ref HEAD)
    git push -u "$remote" "$branch"
fi
