#!/bin/bash

# get full path to the real script directory
# need this to reliably import scripts
SCRIPT=`realpath $0`
DIR=`dirname $SCRIPT`

# shortcuts to be run as, for example
# $ gud c

source "$DIR/_get-options"
options=$(get-options)

declare -A cmds

cache_file="$DIR/.gud-options-cache"

# parsing the file for columns causes a little delay
# so we save the definitions in a cache file so it will load instantly
if [ ! -f "$cache_file" ]; then
    printf "#!/bin/bash\n" > "$cache_file"
    while read -r line; do
        cmd=$(echo "$line" | cut -d'|' -f1| xargs)
        shortcut=$(echo "$line" | cut -d'|' -f2 | xargs)
        printf "cmds[\"$shortcut\"]=\"$cmd\"\n" >> "$cache_file"
    done <<< "$options"
fi

source "$cache_file"

# common functions used in commands
source "$DIR/_run-command"
source "$DIR/_get-branch-name"
source "$DIR/_get-tag-name"
source "$DIR/_get-commit-hash"
source "$DIR/_get-stash-ref"
source "$DIR/_get-remote-name"

if [ -v cmds[$1] ]; then
    # a short cut was used
    # $ gud c
    ${cmds[$1]}
elif [ -f "$DIR/$1" ]; then
    # long-form of the command passed through
    # $ gud checkout-branch
    source "$DIR/$1"
    $1
elif [ -z "$1" ]; then
    # no command passed is the menu shortcut
    # load menu options
    source "$DIR/menu"
    menu
else
    printf "\nError: Unknown command\n\n"
    printf "Run the following to see a list of commands:\n\n"
    printf "$ gud\n"
fi
