#!/bin/bash

history () {
    histfile=~/.config/git-gud/history
    if [ -f "$histfile" ]; then
        tac "$histfile" | awk -F '|' '{printf("\x1b[34;1m%s\x1b[m|\x1b[33;1m%s\x1b[m|%s|%s\n", $1, $2, $3, $4)}' | format-columns | less
    else
        echo "No git-gud history found"
    fi
}
