#!/bin/bash

history () {
    histfile=~/.config/git-gud/history
    if [ -f "$histfile" ]; then
        tac "$histfile" | awk -F '|' '{printf("\x1b[34;1m%-35s\x1b[m\t%-20s\t%s\n", $1, $2, $3)}' | less
    else
        echo "No git-gud history found"
    fi
}
