#!/bin/bash

history-dir () {
    histfile=~/.config/git-gud/history
    dir=$(pwd)
    if [ -f "$histfile" ]; then
        tac "$histfile" | grep "$dir$" | awk -F '|' '{printf("\x1b[34;1m%s\x1b[m|\x1b[33;1m%s\x1b[m|%s|%s\n", $1, $2, $3, $4)}' | format-columns | less
    else
        echo "No git-gud history found"
    fi
}
