#!/bin/bash

menu () {
    if [ -f ~/.options ]; then
        custom_options=$(cat ~/.gud-options)
    else
        custom_options=""
    fi

    all_options=$(printf "$options\n$custom_options")
    target=$(echo "$all_options" | awk -F '|' '{printf("\x1b[34;1m%-25s\x1b[m\t%s\n", $1, $2)}' | fzf --ansi --preview="")

    if [ -n "$target" ]; then
        cmd=$(echo "$target" | awk -F"  " '{print $1}')
        bash -c "$cmd"
    fi
}
