#!/bin/bash

menu () {
    if [ -f ~/.options ]; then
        custom_options=$(cat ~/.gud-options)
    else
        custom_options=""
    fi

    all_options=$(printf "$options\n$custom_options")
    target=$(echo "$all_options" | column -ts '|' | fzf --preview="")

    if [ -n "$target" ]; then
        cmd=$(echo "$target" | awk -F"  " '{print $1}')
        bash -c "$cmd"
    fi
}
