#!/bin/bash

menu () {
    SCRIPT=`realpath $0`
    DIR=`dirname $SCRIPT`
    options=$(get-options "$DIR")
    target=$(echo "$options" | awk -F '|' '{printf("\x1b[34;1m%-25s\t\x1b[33;1m%-6s\x1b[m\t%s\n", $1, $2, $3)}' | fzf --ansi --preview="")

    if [ -n "$target" ]; then
        cmd=$(echo "$target" | awk -F"  " '{print $1}')
        bash -c "$cmd"
    fi
}
