#!/bin/bash

push-tag () {
    local_tags=$(bash -c "comm -23 <(git show-ref --tags | cut -d ' ' -f 2) <(git ls-remote --tags | cut -f 2)" | awk -F"/" '{print $3}')
    tag=$(echo "$local_tags" | fzf --preview='echo "Select a tag. No action is taken until selecting a remote."' --preview-window down:5)

    if [ -z "$tag" ]; then
        exit
    fi

    remote=$(get-remote-name "echo \"git push -u {1} $tag\"")

    if [ -z "$remote" ]; then
        exit
    fi

    run-command "git push -u $remote $tag"
}
