#!/bin/bash

stash-message () {
    echo "git stash push -m \"[your message here]\"";
    read -p "Message: " stash_message

    if [ -n "$stash_message" ]; then
        git stash push -m \""$stash_message"\"
    fi
}
