#!/bin/bash

track-remote () {
    branch=$(git rev-parse --abbrev-ref HEAD)
    remote=$(get-remote-name "echo \"git branch $branch -u {1}/$branch\"")

    if [ -n "$remote" ]; then
        run-command "git branch $branch -u $remote/$branch"
    fi
}
