#!/bin/bash

upstream-push () {
    branch=$(git rev-parse --abbrev-ref HEAD)
    remote=$(get-remote-name "echo \"git push -u {1} $branch\"")

    if [ -n "$remote" ]; then
        run-command "git push -u $remote $branch"
    fi
}
